/**
 * Cute Cards Modal Build Script
 *
 * Bundles modular source files into Shopify theme assets
 * Usage:
 *   node build.js           # Production build
 *   node build.js --watch   # Watch mode for development
 */

const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

const isWatch = process.argv.includes('--watch');
const isProd = !isWatch;

// Build configuration
const config = {
  // JavaScript bundle
  js: {
    entryPoints: ['src/cc-choice/index.js'],
    bundle: true,
    outfile: 'assets/cc-choice.js',
    format: 'iife',
    target: ['es2020'],
    minify: isProd,
    sourcemap: !isProd,
    loader: {
      '.js': 'js' // Explicitly use JS loader, not JSX
    },
    banner: {
      js: `/**
 * Cute Cards Choice Modal
 * Modular architecture - built from src/cc-choice/
 * Do NOT edit this file directly - edit source files instead
 * Build: ${new Date().toISOString()}
 */`
    },
    logLevel: 'info'
  }
};

// CSS bundler (simple concatenation for now)
function bundleCSS() {
  const cssFiles = [
    'src/cc-choice/styles/base.css',
    'src/cc-choice/styles/choice.css',
    'src/cc-choice/styles/personaliser.css',
    'src/cc-choice/styles/mobile.css',
    'src/cc-choice/styles/states.css'
  ];

  const banner = `/**
 * Cute Cards Choice Modal - Styles
 * Modular architecture - built from src/cc-choice/styles/
 * Do NOT edit this file directly - edit source files instead
 * Build: ${new Date().toISOString()}
 */\n\n`;

  let combined = banner;

  for (const file of cssFiles) {
    if (fs.existsSync(file)) {
      const content = fs.readFileSync(file, 'utf-8');
      combined += `/* ========== ${path.basename(file)} ========== */\n\n`;
      combined += content + '\n\n';
    }
  }

  fs.writeFileSync('assets/cc-choice.css', combined, 'utf-8');
  console.log(`✓ Built assets/cc-choice.css`);
}

// Build function
async function build() {
  try {
    console.log(`Building Cute Cards Modal (${isProd ? 'production' : 'development'})...`);

    // Build JavaScript
    if (isWatch) {
      const ctx = await esbuild.context(config.js);
      await ctx.watch();
      console.log('👀 Watching for JavaScript changes...');
    } else {
      await esbuild.build(config.js);
      console.log('✓ Built assets/cc-choice.js');
    }

    // Build CSS
    if (fs.existsSync('src/cc-choice/styles')) {
      bundleCSS();

      if (isWatch) {
        // Watch CSS files
        const cssWatcher = fs.watch('src/cc-choice/styles', { recursive: true }, (eventType, filename) => {
          if (filename && filename.endsWith('.css')) {
            console.log(`Changed: ${filename}`);
            bundleCSS();
          }
        });
        console.log('👀 Watching for CSS changes...');
      }
    }

    if (!isWatch) {
      console.log('✓ Build complete!');
    }

  } catch (error) {
    console.error('❌ Build failed:', error);
    process.exit(1);
  }
}

// Run build
build();
